📰👾 save surviving mutants registry

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -68,6 +68,11 @@ jobs:
       with:
         name: mutant registry
         path: html
+    - name: Fail if file 'registry' exists
+      if: ${{ success() }}
+      run: |
+        echo "❌ Mutants failing. Check file mutants registry exists."
+        exit 1
 
   deploy-image-and-package:
     needs: run-tests
